# Generated by Django 3.2 on 2021-05-31 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_tracker', '0002_auto_20210524_1923'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Action',
        ),
    ]
